### ISSUE TITLE
Improve snapshot restoration for blockchain node charts

### ISSUE THREAD

**Issue by chriswessels** [graphops/launchpad-charts#116]
- [ ] Update docker-builds/init-toolkit with a suite of download and extraction tools
- [ ] Allowing specifying custom script (with env vars for things like the persistent data path) in the initContainer that handles snapshot restoration
- [ ] Update documentation to show handling common formats with aria2c or other tools
- [ ] Document how download-resumption works

**Comment by matthewdarwin** [comment]
Also support downloading from S3 bucket, which would require AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY

**Comment by matthewdarwin** [comment]
Also support zstd and lz4 compression.  Different snapshot providers use different compression algorithms. (They probably also use different directory layouts, additional challenge)
