### ISSUE TITLE
common: implement a Templating preProcessor

### ISSUE THREAD

**Issue by cjorge-graphops** [graphops/launchpad-charts#428]
Currently we're lacking a proper solution to address templating values that themselves depend on other values.
Some avenues have been considered:
1) do not support it altogether
2) support 2 or 3-level tiered templating where a set of values is templated first, a set templated last (or in the middle, and then a 3rd set last)

We're forced to dismiss 1) because the implications of a complete lack of this feature make it impractical to handle (common) use-cases.

2) feels like a compromise that still requires some solution to differentiate the templating order among values: i.e. regex matched embedded special syntax on the template, or some standardized special key that adds suffixes or prefixes to the values they mark like myvalue: "{{ template }}" and then the key __myvalue_tplLast existing for example. This ends up being unelegant and cumbersome, and is already non trivial to handle.

Lastly, there is a (much less impactful) shortcoming on the current templating logic which is that it leverages YAML serializing/unserializing functions to autodetect templating result value types. While this is good 99% of the time, in some corner cases it makes it impossible to get the desired value type which can be problematic.

If we implement a proper preProcessor, we can fully address both of these issues.
Proposal:
- [x] support two preprocessing macros like @needs/@eval, and @type embedded in the template strings, like:
'{{ my template }}{{ more logic }}{{ end }} @needs(.some.value.path as varName)' @type(str)'
- [x] before processing the templates, regexMatch the strings for those macros and extract them
- [x] use the @type hints, when they exist, to cast the result of the template (this will rarely be needed, but no other solution when it IS needed)
- [x] build a list of needed values with the @needs declarations: all referenced values should be declared as needed. Template those recursively first and then prefix the templating code with {{ $varName := evaluationResult }}. The templates are then expected to instead having to refer to the paths, just use the variable $varName for each of their desired inputs. Do the most basic cycle detection to error out on loops.

Later this can be made nicer and more efficient by:
- [x] caching already previously evaluated values
- [ ] as an end game: build a DAG and evaluate it optimally
but neither of those will be urgent in terms of real-world performance mandating it.

As a side effect of this approach, configuration management logic will also be made much more readable/cleaner because it will be referring to single keyword variables like $someVar , and all the long paths can come in the string at the tail. Right now, there is often a lot of uninteresting cruft or repetition of long paths that makes simple logical expressions look long and less clear.
